version: '3.9'

services:
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '2500:2500'
      - '4444:8080'
      - '8085:8085'
  mysql:
    image: eu.gcr.io/serlo-shared/serlo-mysql-database:latest
    platform: linux/x86_64
    pull_policy: always
    ports:
      - '3306:3306'
