version: '3.9'

services:
  # TODO: at the moment we need to start api and with it also kratos and db layer separately
  # uncomment when api is properly mocked for local development see https://github.com/serlo/notification-mail-service/issues/36
  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '2500:2500'
      - '4444:8080'
      - '8085:8085'
