version: '3.9'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '2500:2500'
      - '8080:8080'
      - '8085:8085'