export const strings = {
  entities: {
    applet: 'एप्लेट',
    article: 'लेख',
    course: 'पाठ्यक्रम',
    coursePage: 'अध्ययन पृष्ठ',
    event: 'कार्यक्रम',
    exercise: 'अभ्यास',
    exerciseGroup: 'व्यायाम समूह',
    topic: 'Folder',
    groupedExercise: 'समूह व्यायाम',
    page: 'पृष्ठ',
    solution: 'हल',
    taxonomyTerm: 'टैक्सोनोमी शब्द',
    user: 'उपयोगकर्ता',
    video: 'वीडियो',
    exerciseFolder: 'Exercise folder',
    comment: 'टिप्पणियां',
    revision: 'संशोधन',
    thread: 'धागा',
    threads: 'थ्रेडस',
    subject: 'विषय',
    userProfile: 'यूज़र प्रोफाइल',
    privacyPolicy: 'गोपनीयता नीति',
    content: 'सामग्री',
  },
  events: {
    entityInParentPreposition: 'in',
    commentInParentPreposition: 'on',
    setThreadStateArchived: '%actor% archived %thread%.',
    setThreadStateUnarchived: '%actor% restored %thread%.',
    createComment: '%actor% commented in %thread%: %comment%.',
    createThread: '%actor% started %thread% on %object%.',
    createEntity: '%actor% created %object%.',
    setLicense: '%actor% changed the license of %repository%.',
    createEntityLink: '%actor% associated %child% with %parent%.',
    removeEntityLink: '%actor% dissociated %child% from %parent%.',
    createEntityRevision: '%actor% created %revision% of %entity%.',
    checkoutRevision: '%actor% checked out %revision% in %repository%.',
    rejectRevision: '%actor% did not accept %revision% in %repository%.',
    createTaxonomyLink: '%actor% added %child% to %parent%.',
    removeTaxonomyLink: '%actor% removed %child% from %parent%.',
    createTaxonomyTerm: '%actor% created %term%.',
    setTaxonomyTerm: '%actor% updated %term%.',
    setTaxonomyParentDeleted: '%actor% removed the parent of %child%.',
    setTaxonomyParentChangedFrom:
      '%actor% changed parent of %child% from %previousparent% to %parent%.',
    setTaxonomyParentChanged: '%actor% changed parent of %child% to %parent%.',
    setUuidStateTrashed: '%actor% trashed %object%.',
    setUuidStateRestored: '%actor% restored %object%.',
    inviteToChat:
      '%actor% invited you to the Chat: %comment% Go to %chatLink% to chat with %actor% and others.',
    entityPlaceholderFallback: 'Content',
  },
  email: {
    //TODO: translate
    subject: 'You have unread notifications on Serlo',
    greeting: 'Hello %username%!',
    initiation:
      "Here's a heads up of what has happened with content you edited or created:",
    settings:
      'You can %link% for which content you want to receive notifications.',
    linkText: 'change the settings',
  },
}
