export const EVENT_TYPE = {
    TAXONOMY_TERM_ASSOCIATE: 1,
    TAXONOMY_TERM_CREATE: 2,
    LICENSE_OBJECT_SET: 3,
    ENTITY_CREATE: 4,
    ENTITY_REVISION_ADD: 5,
    ENTITY_REVISION_CHECKOUT: 6,
    ENTITY_LINK_CREATE: 7,
    DISCUSSION_CREATE: 8,
    DISCUSSION_COMMENT_CREATE: 9,
    UUID_TRASH: 10,
    ENTITY_REVISION_REJECT: 11,
    TAXONOMY_TERM_UPDATE: 12,
    UUID_RESTORE: 13,
    DISCUSSION_COMMENT_ARCHIVE: 14,
    TAXONOMY_TERM_PARENT_CHANGE: 15,
    DISCUSSION_RESTORE: 16,
    TAXONOMY_TERM_DISSOCIATE: 17,
    ENTITY_LINK_REMOVE: 18,
};

export const RADIX_TYPE = {
    BINARY: 2,
    OCTAL: 8,
    DECIMAL : 10,
    HEXADECIMAL: 16,
}