export interface LanguageStrings {
  entities: {
    applet: string
    article: string
    course: string
    coursePage: string
    event: string
    exercise: string
    exerciseGroup: string
    topic: string
    groupedExercise: string
    page: string
    solution: string
    taxonomyTerm: string
    user: string
    video: string
    exerciseFolder: string
    comment: string
    revision: string
    thread: string
    threads: string
    subject: string
    userProfile: string
    privacyPolicy: string
    content: string
  }
  events: {
    entityInParentPreposition: string
    commentInParentPreposition: string
    setThreadStateArchived: string
    setThreadStateUnarchived: string
    createComment: string
    createThread: string
    createEntity: string
    setLicense: string
    createEntityLink: string
    removeEntityLink: string
    createEntityRevision: string
    checkoutRevision: string
    rejectRevision: string
    createTaxonomyLink: string
    removeTaxonomyLink: string
    createTaxonomyTerm: string
    setTaxonomyTerm: string
    setTaxonomyParentDeleted: string
    setTaxonomyParentChangedFrom: string
    setTaxonomyParentChanged: string
    setUuidStateTrashed: string
    setUuidStateRestored: string
    inviteToChat: string
    entityPlaceholderFallback: string
  }
  email: {
    subject: string
    greeting: string
    initiation: string
    settings: string
    linkText: string
  }
}
