name: CI Checks
on: [push, merge_group]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:tsc

  test_unit:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn test:unit

  test_e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: ./scripts/e2e_test.sh
